# Práctica 1.1 — Probabilidad y Estadística - Análisis de la evolución poblacional mundial 
## Actividad 1 — Identificación de la fuente 
### Issabela Romero - 82275

CITA. UN, World Population Prospects (2024) – processed by Our World in Data. “Annual change in population – UN WPP” [dataset]. United Nations, “World Population Prospects”; United Nations, “World Population Prospects - Interim Update” [original data]. 

Preguntas:

¿Quién produjo originalmente los datos? United Nations

¿Qué organización los procesa para su utilización en Our World in Data? Our World in Data

¿Qué representa la variable que analizarás? annual population growth

## Actividad 2 — Carga y exploración de datos

In [1]:
import pandas as pd 

import numpy as np 

dataframe = pd.read_csv("C:\\Users\\Romero Aguayo\\Documents\\LASALLE\\SEMESTRE 5\\TOPICOS BIG DATA\\U1_1_PRUEBA\\data\\raw\\annual-population-growth\\annual-population-growth.csv")

dataframe

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN
...,...,...,...,...,...
38395,Zimbabwe,ZWE,2096,NaN,100752.0
38396,Zimbabwe,ZWE,2097,NaN,91796.0
38397,Zimbabwe,ZWE,2098,NaN,87605.0
38398,Zimbabwe,ZWE,2099,NaN,76670.0
38399,Zimbabwe,ZWE,2100,NaN,70019.0

In [2]:
dataframe.shape

(38400, 5)

In [3]:
dataframe.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [4]:
dataframe.dtypes

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [5]:
dataframe.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [6]:
dataframe.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [7]:
dataframe["Entity"].nunique()

256

In [8]:
dataframe_extraccion_entity = dataframe[["Entity","Year"]]
dataframe_extraccion_entity

            Entity  Year
0      Afghanistan  1951
1      Afghanistan  1952
2      Afghanistan  1953
3      Afghanistan  1954
4      Afghanistan  1955
...            ...   ...
38395     Zimbabwe  2096
38396     Zimbabwe  2097
38397     Zimbabwe  2098
38398     Zimbabwe  2099
38399     Zimbabwe  2100

[38400 rows x 2 columns]

In [9]:
dataframe2020 = dataframe[dataframe["Year"]==2020]
dataframe2020.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN

In [10]:
dataframe_extraccion2020 = dataframe2020[["Entity","Year"]]
dataframe_extraccion2020.head(3)

          Entity  Year
69   Afghanistan  2020
219  Africa (UN)  2020
369      Albania  2020

In [11]:
dataframe_extraccion2020_2 = dataframe[dataframe["Year"]==2020][["Entity","Year"]]
dataframe_extraccion2020_2.head(3)

          Entity  Year
69   Afghanistan  2020
219  Africa (UN)  2020
369      Albania  2020

In [12]:
dataframe_2005_2020 = dataframe[(dataframe["Year"]>=2005) & (dataframe["Year"]<=2020)]
dataframe_2005_2020.shape

(4096, 5)

In [13]:
dataframe_2005_2020MEX = dataframe[(dataframe["Year"]>=2005) & (dataframe["Year"]<=2020) & (dataframe["Entity"]=="Mexico")]
dataframe_2005_2020MEX.shape

(16, 5)

In [14]:
dataframe.loc[:,"Entity"]

0        Afghanistan
1        Afghanistan
2        Afghanistan
3        Afghanistan
4        Afghanistan
            ...
38395       Zimbabwe
38396       Zimbabwe
38397       Zimbabwe
38398       Zimbabwe
38399       Zimbabwe
Name: Entity, Length: 38400, dtype: str

In [20]:
dataframe.iloc[600:610,0:2]

             Entity Code
600  American Samoa  ASM
601  American Samoa  ASM
602  American Samoa  ASM
603  American Samoa  ASM
604  American Samoa  ASM
605  American Samoa  ASM
606  American Samoa  ASM
607  American Samoa  ASM
608  American Samoa  ASM
609  American Samoa  ASM